name: "nllb-multi-domain"

data:
  path: "breakend/nllb-multi-domain"
  source_lang: eng_Latn
  target_lang: rus_Cyrl
  dataset_config_name: "eng_Latn-rus_Cyrl"

model:
  # name: "facebook/nllb-200-distilled-1.3B"
  name: "facebook/nllb-200-distilled-600M"
  # name: "model/"
  # name: "facebook/nllb-200-3.3B"
  use_lora: false
  lora:
    r: 8
    alpha: 32
    dropout: 0.05
    target_modules:
      - q_proj
      - v_proj

training:
  lr: 0.000002
  accumulate_grad_batches: 1
  epochs: 3
  batch_size: 2
  num_return_sequences: 4
  updates_per_batch: 1
  gen_temperature: 1.8
  beta: 0.04
  clip_param: 0.2
  top_k: 100
  top_p: 0.95
  use_wandb: true
  log_every_n_steps: 5
  update_ref_policy_every_n_steps: 16
  
eval:
  run: true
  only: false
  translation_metric: ["chrf++"]
  every_n_opt_steps: 5

test:
  run: true
  translation_metric: ["chrf++"]

reward:
  # MT reward settings (BLEU and chrF++)
  bleu_weight: 0.0  # Weight for BLEU score
  chrf_weight: 0.5  # Weight for chrF++ score
  length_penalty_weight: 0.1
  goldfish_reward_weight: 0.4
constraints: 
  min_sentence_len: 1
  max_sentence_len: 63 # excluding first eos and langid tokens
