name: "nllb-multi-domain"

data:
  path: "breakend/nllb-multi-domain"
  source_lang: eng_Latn
  target_lang: ayr_Latn
  dataset_config_name: "eng_Latn-ayr_Latn"

model:
  name: "facebook/nllb-200-distilled-600M"
  # name: "facebook/nllb-200-3.3B"
  use_lora: false
  lora:
    r: 8
    alpha: 32
    dropout: 0.05
    target_modules:
      - q_proj
      - v_proj

training:
  lr: 0.00005
  accumulate_grad_batches: 1
  epochs: 10
  batch_size: 1
  num_return_sequences: 4
  updates_per_batch: 30
  gen_temperature: 1.3
  beta: 0.04
  clip_param: 0.2
  top_k: 100
  top_p: 0.99

eval:
  run: true
  only: false
  translation_metric: ["chrf++"]
  every_n_batches: 50

reward:
  # MT reward settings (BLEU and chrF++)
  bleu_weight: 0.5  # Weight for BLEU score
  chrf_weight: 0.5  # Weight for chrF++ score


constraints:
  min_sentence_len: 1
  max_sentence_len: 256
