name: "nllb-multi-domain"

data:
  path: "breakend/nllb-multi-domain"
  source_lang: eng_Latn
  target_lang: ayr_Latn
  dataset_config_name: "eng_Latn-ayr_Latn"

model:
  name: "facebook/nllb-200-distilled-600M"

training:
  pf_temp_high: 0.4
  pf_temp_low: 0.2
  pf_temp_prob: 0.666
  use_buffer_prob: 0.25
  n_samples: 2
  lr: 0.0001
  accumulate_grad_batches: 1
  epochs: 2

eval:
  n_probes: 10
  translation_metric: ["bleu", "chrf"]

reward:
  temp_start: 1.0
  temp_end: 0.8
  temp_horizon: 750
  vocab_alpha: -50
  sentence_validator: null
  buffer_size: 50
  # MT reward settings (BLEU and chrF++)
  bleu_weight: 0.5  # Weight for BLEU score
  chrf_weight: 0.5  # Weight for chrF++ score

callbacks:
  - _target_: pytorch_lightning.callbacks.ModelCheckpoint
    monitor: "val/chrf"
    mode: "max"
    save_last: True
    dirpath: ${save_dir}/checkpoints/${now:%Y-%m-%d}_${now:%H-%M-%S}
    filename: "epoch={epoch:03d}"
    auto_insert_metric_name: True
  - _target_: pytorch_lightning.callbacks.EarlyStopping
    monitor: "val/chrf"
    mode: "max"
    patience: 10

constraints:
  min_sentence_len: 1
  max_sentence_len: 256